### ISSUE TITLE
Move persistance of events to publisher not reciever

### ISSUE THREAD

**Issue by douggie** [timolson/cointrader#104]
Due to esper and cointraders multi threaded nature it is probably more performant and robust (in case message is never recived) to persist events once they have been published, this means their is an oppurtunity for the event to be recivied by a seperate thread whilst the publishing thread persists. If the persit fails then we have incomplete state.

**Comment by timolson** [comment]
Before you dive too deeply into this, check out the various threading options within Esper.  There is a mode whereby the publishing thread is separated from the receiving subscription threads.  Is this what you want?  Or is this ticket more about durability?

**Comment by douggie** [comment]
Hi tim, all the treading options are now supportted and cointrader works
with multiple inbound and outbound threads.

This is more about durability so to ensure peesistance event if the event
is not recivied. In addition if tge reciver is on a seperate thread it can
just get on with its work whilst the sender persists.

Just thought it felt better to ensure events are persisted by the publisher
rather than reciver.

**Comment by timolson** [comment]
If it's all about durability, we should save data as far upstream as possible.  Maybe the XChange adapter should be saving raw API data immediately to disk before parsing.  That way, if there is any API change which prevents data parsing, we will still have the raw data to process later, after the adapter is fixed.  However, this is surely a modification to XChange not Coin Trader…

**Comment by douggie** [comment]
Cool. Will make the changes to persit as the event is instiated.
