### ISSUE TITLE
EntityNotFoundException when merging Position with cascades

### ISSUE THREAD

**Issue by douggie** [timolson/cointrader#114]
When trying to persit a postion with the folloiwng annotations using multiple threads the following execption occurs, dispite the the fill being persited.

Fill
```java
    public @ManyToOne(optional = true, cascade = { CascadeType.MERGE, CascadeType.REMOVE, CascadeType.REFRESH })
    @JoinColumn(name = "position")
    Position getPosition() {
        return position;
    }
```

Position
```java
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "position", cascade = { CascadeType.MERGE, CascadeType.REFRESH })
    @NotFound(action = NotFoundAction.IGNORE)
    public Collection<Fill> getFills() {
        if (fills == null)
            fills = new ConcurrentLinkedQueue<Fill>();
        return fills;

    }
```

Position constructor

```java
public Position(Fill fill) {

        this.addFill(fill);
        this.exchange = fill.getMarket().getExchange();
        this.market = fill.getMarket();
        this.volume = fill.getVolume();
        this.volumeCount = volume.toBasis(market.getVolumeBasis(), Remainder.ROUND_EVEN).getCount();
        this.longVolume = volume.isPositive() ? volume : this.longVolume;
        this.longVolumeCount = volume.isPositive() ? volume.toBasis(market.getVolumeBasis(), Remainder.ROUND_EVEN).getCount() : this.longVolumeCount;
        this.shortVolume = volume.isNegative() ? volume : this.shortVolume;
        this.shortVolumeCount = volume.isNegative() ? volume.toBasis(market.getVolumeBasis(), Remainder.ROUND_EVEN).getCount() : this.shortVolumeCount;
        this.longAvgPrice = volume.isPositive() ? fill.getPrice() : this.longAvgPrice;
        this.shortAvgPrice = volume.isNegative() ? fill.getPrice() : this.shortAvgPrice;
        this.shortAvgStopPrice = fill.getStopPrice() != null && fill.isShort() ? fill.getStopPrice() : DecimalAmount.ZERO;
        this.longAvgStopPrice = fill.getStopPrice() != null && fill.isLong() ? fill.getStopPrice() : DecimalAmount.ZERO;
        this.asset = fill.getMarket().getListing().getBase();

        this.portfolio = fill.getPortfolio();
        fill.setPosition(this);
        fill.getPortfolio().addPosition(this);

    }
```

```
javax.persistence.EntityNotFoundException: Unable to find org.cryptocoinpartners.schema.Fill with id 9afc29d3-df3d-490f-8545-54d228bf1dce
```
Thoughts
1. As adding the fill to the position within the position constructor rather than the fill constructor is confusing JPA
2. another thread is removing the fill from the position before it has been persisted.

**Comment by douggie** [comment]
updated:

        public @ManyToOne(optional = true, cascade = { CascadeType.MERGE, CascadeType.REFRESH })
        @JoinColumn(name = "position")
        Position getPosition() {
            return position;
        }

**Comment by timolson** [comment]
I don't know much about JPA cascading, but if it does the obvious thing, then you should only have to set   the relationship in one place.  Also, what does the call to `merge()` look like?  You just use `PersistUtil`?

We "should" be JPA threadsafe from earlier work.

**Comment by douggie** [comment]
yes just persitUtil.merege

**Comment by douggie** [comment]
public static void merge(EntityBase... entities) {

        EntityManager em = null;

        boolean persited = true;

        try {

            em = createEntityManager();

            em.setProperty("javax.persistence.cache.storeMode",
CacheStoreMode.REFRESH);


            PersistUtilHelper.beginTransaction();


            try {

                for (EntityBase entity : entities) {

                    //em.find(entity.getClass(), entity.getId());

                    em.merge(entity);

                    PersistUtilHelper.commit();

                }


            } catch (Exception | Error e) {

                persited = false;

                e.printStackTrace();

                if (PersistUtilHelper.isActive())

                    PersistUtilHelper.rollback();

            }

        } finally {

            if (persited)

                for (EntityBase entity : entities)

                    log.debug(entity.getClass().getSimpleName() + ": " +
entity.getId().toString() + " saved to database");

            else

                for (EntityBase entity : entities)

                    log.error(entity.getClass().getSimpleName() + ": " +
entity.getId().toString() + " not saved to database");

            if (em != null && em.isOpen())

                PersistUtilHelper.closeEntityManager();


        }

    }

**Comment by douggie** [comment]
all i can think is that another thread has removed it from the position and
persited it, before the later thread comes along and tried to persit an
older position, but I don't see why it would say the fill is not found if
it is their.

I will turn on logging, sometime jpa gives you an error that is not where
the problem is.

**Comment by douggie** [comment]
so the following works
select hex(id) from fill where fill.id=unhex('05c5648c00444f5a9d3b1ee7d54325aa')

but the query jpa runs does also return
select fill0_.id as id1_10_0_, fill0_.version as version2_10_0_, fill0_.time as time3_10_0_, fill0_.remote_key as remote_k4_10_0_, fill0_.time_received as time_rec5_10_0_, fill0_.market as market11_10_0_, fill0_.open_volume_count as open_vol6_10_0_, fill0_.`order` as order12_10_0_, fill0_.portfolio as portfol13_10_0_, fill0_.position as positio14_10_0_, fill0_.price_count as price_co7_10_0_, fill0_.stop_price_count as stop_pri8_10_0_, fill0_.target_price_count as target_p9_10_0_, fill0_.volume_count as volume_10_10_0_, children1_.fill as fill1_10_1_, order2_.id as children2_0_1_, order2_.id as id1_2_2_, order2_.version as version2_2_2_, order2_.time as time3_2_2_, order2_.comment as comment4_2_2_, order2_.emulation as emulatio5_2_2_, order2_.entry_time as entry_ti6_2_2_, order2_.expiration as expirati7_2_2_, order2_.fill_type as fill_typ8_2_2_, order2_.margin_type as margin_t9_2_2_, order2_.market as market12_2_2_, order2_.panic_force as panic_f10_2_2_, order2_.`parent_order` as parent_13_2_2_, order2_.portfolio as portfol14_2_2_, order2_.position_effect as positio11_2_2_, order2_.limit_price_decimal as limit_pr1_11_2_, order2_.listing as listing8_11_2_, order2_.market as market12_11_2_, order2_.stop_amount_decimal as stop_amo2_11_2_, order2_.stop_price_decimal as stop_pri3_11_2_, order2_.target_amount_decimal as target_a4_11_2_, order2_.target_price_decimal as target_p5_11_2_, order2_.trailing_stop_price_decimal as trailing6_11_2_, order2_.volume_decimal as volume_d7_11_2_, order2_.limit_price_count as limit_pr1_27_2_, order2_.market as market12_27_2_, order2_.placement_count as placemen2_27_2_, order2_.remote_key as remote_k3_27_2_, order2_.time_received as time_rec4_27_2_, order2_.volume_count as volume_c5_27_2_, order2_.clazz_ as clazz_2_, children3_.`order` as order1_2_3_, order4_.id as children2_1_3_, order4_.id as id1_2_4_, order4_.version as version2_2_4_, order4_.time as time3_2_4_, order4_.comment as comment4_2_4_, order4_.emulation as emulatio5_2_4_, order4_.entry_time as entry_ti6_2_4_, order4_.expiration as expirati7_2_4_, order4_.fill_type as fill_typ8_2_4_, order4_.margin_type as margin_t9_2_4_, order4_.market as market12_2_4_, order4_.panic_force as panic_f10_2_4_, order4_.`parent_order` as parent_13_2_4_, order4_.portfolio as portfol14_2_4_, order4_.position_effect as positio11_2_4_, order4_.limit_price_decimal as limit_pr1_11_4_, order4_.listing as listing8_11_4_, order4_.market as market12_11_4_, order4_.stop_amount_decimal as stop_amo2_11_4_, order4_.stop_price_decimal as stop_pri3_11_4_, order4_.target_amount_decimal as target_a4_11_4_, order4_.target_price_decimal as target_p5_11_4_, order4_.trailing_stop_price_decimal as trailing6_11_4_, order4_.volume_decimal as volume_d7_11_4_, order4_.limit_price_count as limit_pr1_27_4_, order4_.market as market12_27_4_, order4_.placement_count as placemen2_27_4_, order4_.remote_key as remote_k3_27_4_, order4_.time_received as time_rec4_27_4_, order4_.volume_count as volume_c5_27_4_, order4_.clazz_ as clazz_4_, fills5_.`order` as order12_2_5_, fills5_.id as id1_10_5_, fills5_.id as id1_10_6_, fills5_.version as version2_10_6_, fills5_.time as time3_10_6_, fills5_.remote_key as remote_k4_10_6_, fills5_.time_received as time_rec5_10_6_, fills5_.market as market11_10_6_, fills5_.open_volume_count as open_vol6_10_6_, fills5_.`order` as order12_10_6_, fills5_.portfolio as portfol13_10_6_, fills5_.position as positio14_10_6_, fills5_.price_count as price_co7_10_6_, fills5_.stop_price_count as stop_pri8_10_6_, fills5_.target_price_count as target_p9_10_6_, fills5_.volume_count as volume_10_10_6_, market6_.id as id1_13_7_, market6_.version as version2_13_7_, market6_.active as active3_13_7_, market6_.exchange as exchange6_13_7_, market6_.listing as listing7_13_7_, market6_.price_basis as price_ba4_13_7_, market6_.volume_basis as volume_b5_13_7_, order7_.id as id1_2_8_, order7_.version as version2_2_8_, order7_.time as time3_2_8_, order7_.comment as comment4_2_8_, order7_.emulation as emulatio5_2_8_, order7_.entry_time as entry_ti6_2_8_, order7_.expiration as expirati7_2_8_, order7_.fill_type as fill_typ8_2_8_, order7_.margin_type as margin_t9_2_8_, order7_.market as market12_2_8_, order7_.panic_force as panic_f10_2_8_, order7_.`parent_order` as parent_13_2_8_, order7_.portfolio as portfol14_2_8_, order7_.position_effect as positio11_2_8_, order7_.limit_price_decimal as limit_pr1_11_8_, order7_.listing as listing8_11_8_, order7_.market as market12_11_8_, order7_.stop_amount_decimal as stop_amo2_11_8_, order7_.stop_price_decimal as stop_pri3_11_8_, order7_.target_amount_decimal as target_a4_11_8_, order7_.target_price_decimal as target_p5_11_8_, order7_.trailing_stop_price_decimal as trailing6_11_8_, order7_.volume_decimal as volume_d7_11_8_, order7_.limit_price_count as limit_pr1_27_8_, order7_.market as market12_27_8_, order7_.placement_count as placemen2_27_8_, order7_.remote_key as remote_k3_27_8_, order7_.time_received as time_rec4_27_8_, order7_.volume_count as volume_c5_27_8_, order7_.clazz_ as clazz_8_, portfolio8_.id as id1_20_9_, portfolio8_.version as version2_20_9_, portfolio8_.base_asset as base_ass4_20_9_, portfolio8_.name as name3_20_9_, transactio9_.`order` as order15_2_10_, transactio9_.id as id1_33_10_, transactio9_.id as id1_33_11_, transactio9_.version as version2_33_11_, transactio9_.time as time3_33_11_, transactio9_.amount_count as amount_c4_33_11_, transactio9_.asset as asset9_33_11_, transactio9_.commission_count as commissi5_33_11_, transactio9_.commission_currency as commiss10_33_11_, transactio9_.currency as currenc11_33_11_, transactio9_.exchange as exchang12_33_11_, transactio9_.fill as fill13_33_11_, transactio9_.market as market14_33_11_, transactio9_.`order` as order15_33_11_, transactio9_.portfolio as portfol16_33_11_, transactio9_.position_effect as position6_33_11_, transactio9_.price_count as price_co7_33_11_, transactio9_.type as type8_33_11_, listing10_.id as id1_12_12_, listing10_.version as version2_12_12_, listing10_.base as base3_12_12_, listing10_.prompt as prompt4_12_12_, listing10_.quote as quote5_12_12_, market11_.id as id1_13_13_, market11_.version as version2_13_13_, market11_.active as active3_13_13_, market11_.exchange as exchange6_13_13_, market11_.listing as listing7_13_13_, market11_.price_basis as price_ba4_13_13_, market11_.volume_basis as volume_b5_13_13_, exchange12_.id as id1_9_14_, exchange12_.version as version2_9_14_, exchange12_.fee_method as fee_meth3_9_14_, exchange12_.fee_rate as fee_rate4_9_14_, exchange12_.margin as margin5_9_14_, exchange12_.margin_fee_method as margin_f6_9_14_, exchange12_.margin_fee_rate as margin_f7_9_14_, exchange12_.symbol as symbol8_9_14_, listing13_.id as id1_12_15_, listing13_.version as version2_12_15_, listing13_.base as base3_12_15_, listing13_.prompt as prompt4_12_15_, listing13_.quote as quote5_12_15_, portfolio14_.id as id1_20_16_, portfolio14_.version as version2_20_16_, portfolio14_.base_asset as base_ass4_20_16_, portfolio14_.name as name3_20_16_, asset15_.id as id1_5_17_, asset15_.version as version2_5_17_, asset15_.basis as basis3_5_17_, asset15_.symbol as symbol4_5_17_, asset15_.fiat as fiat1_8_17_, asset15_.clazz_ as clazz_17_, positions16_.portfolio as portfoli1_20_18_, position17_.id as position2_22_18_, position17_.id as id1_24_19_, position17_.version as version2_24_19_, position17_.asset as asset3_24_19_, position17_.exchange as exchange4_24_19_, position17_.market as market5_24_19_, position17_.portfolio as portfoli6_24_19_, stakes18_.portfolio as portfoli1_20_20_, stake19_.id as stakes2_23_20_, stake19_.id as id1_28_21_, stake19_.version as version2_28_21_, stake19_.owner as owner4_28_21_, stake19_.portfolio as portfoli5_28_21_, stake19_.stake as stake3_28_21_, position20_.id as id1_24_22_, position20_.version as version2_24_22_, position20_.asset as asset3_24_22_, position20_.exchange as exchange4_24_22_, position20_.market as market5_24_22_, position20_.portfolio as portfoli6_24_22_, asset21_.id as id1_5_23_, asset21_.version as version2_5_23_, asset21_.basis as basis3_5_23_, asset21_.symbol as symbol4_5_23_, asset21_.fiat as fiat1_8_23_, asset21_.clazz_ as clazz_23_, exchange22_.id as id1_9_24_, exchange22_.version as version2_9_24_, exchange22_.fee_method as fee_meth3_9_24_, exchange22_.fee_rate as fee_rate4_9_24_, exchange22_.margin as margin5_9_24_, exchange22_.margin_fee_method as margin_f6_9_24_, exchange22_.margin_fee_rate as margin_f7_9_24_, exchange22_.symbol as symbol8_9_24_, market23_.id as id1_13_25_, market23_.version as version2_13_25_, market23_.active as active3_13_25_, market23_.exchange as exchange6_13_25_, market23_.listing as listing7_13_25_, market23_.price_basis as price_ba4_13_25_, market23_.volume_basis as volume_b5_13_25_, portfolio24_.id as id1_20_26_, portfolio24_.version as version2_20_26_, portfolio24_.base_asset as base_ass4_20_26_, portfolio24_.name as name3_20_26_ from fill fill0_ left outer join `fill_children` children1_ on fill0_.id=children1_.fill left outer join ( select id, version, time, comment, emulation, entry_time, expiration, fill_type, margin_type, panic_force, position_effect, market, `parent_order`, portfolio, limit_price_decimal, stop_amount_decimal, stop_price_decimal, target_amount_decimal, target_price_decimal, trailing_stop_price_decimal, volume_decimal, listing, null as limit_price_count, null as placement_count, null as remote_key, null as time_received, null as volume_count, 1 as clazz_ from general_order union select id, version, time, comment, emulation, entry_time, expiration, fill_type, margin_type, panic_force, position_effect, market, `parent_order`, portfolio, null as limit_price_decimal, null as stop_amount_decimal, null as stop_price_decimal, null as target_amount_decimal, null as target_price_decimal, null as trailing_stop_price_decimal, null as volume_decimal, null as listing, limit_price_count, placement_count, remote_key, time_received, volume_count, 2 as clazz_ from specific_order ) order2_ on children1_.`children`=order2_.id left outer join `order_children` children3_ on order2_.id=children3_.`order` left outer join ( select id, version, time, comment, emulation, entry_time, expiration, fill_type, margin_type, panic_force, position_effect, market, `parent_order`, portfolio, limit_price_decimal, stop_amount_decimal, stop_price_decimal, target_amount_decimal, target_price_decimal, trailing_stop_price_decimal, volume_decimal, listing, null as limit_price_count, null as placement_count, null as remote_key, null as time_received, null as volume_count, 1 as clazz_ from general_order union select id, version, time, comment, emulation, entry_time, expiration, fill_type, margin_type, panic_force, position_effect, market, `parent_order`, portfolio, null as limit_price_decimal, null as stop_amount_decimal, null as stop_price_decimal, null as target_amount_decimal, null as target_price_decimal, null as trailing_stop_price_decimal, null as volume_decimal, null as listing, limit_price_count, placement_count, remote_key, time_received, volume_count, 2 as clazz_ from specific_order ) order4_ on children3_.`children`=order4_.id left outer join fill fills5_ on order2_.id=fills5_.`order` left outer join market market6_ on order2_.market=market6_.id left outer join ( select id, version, time, comment, emulation, entry_time, expiration, fill_type, margin_type, panic_force, position_effect, market, `parent_order`, portfolio, limit_price_decimal, stop_amount_decimal, stop_price_decimal, target_amount_decimal, target_price_decimal, trailing_stop_price_decimal, volume_decimal, listing, null as limit_price_count, null as placement_count, null as remote_key, null as time_received, null as volume_count, 1 as clazz_ from general_order union select id, version, time, comment, emulation, entry_time, expiration, fill_type, margin_type, panic_force, position_effect, market, `parent_order`, portfolio, null as limit_price_decimal, null as stop_amount_decimal, null as stop_price_decimal, null as target_amount_decimal, null as target_price_decimal, null as trailing_stop_price_decimal, null as volume_decimal, null as listing, limit_price_count, placement_count, remote_key, time_received, volume_count, 2 as clazz_ from specific_order ) order7_ on order2_.`parent_order`=order7_.id left outer join portfolio portfolio8_ on order2_.portfolio=portfolio8_.id left outer join transaction transactio9_ on order2_.id=transactio9_.`order` left outer join listing listing10_ on order2_.listing=listing10_.id left outer join market market11_ on fill0_.market=market11_.id left outer join exchange exchange12_ on market11_.exchange=exchange12_.id left outer join listing listing13_ on market11_.listing=listing13_.id inner join portfolio portfolio14_ on fill0_.portfolio=portfolio14_.id left outer join ( select id, version, basis, symbol, fiat, 1 as clazz_ from currency ) asset15_ on portfolio14_.base_asset=asset15_.id left outer join portfolio_positions positions16_ on portfolio14_.id=positions16_.portfolio left outer join position position17_ on positions16_.positions=position17_.id left outer join portfolio_stakes stakes18_ on portfolio14_.id=stakes18_.portfolio left outer join stake stake19_ on stakes18_.stakes=stake19_.id left outer join position position20_ on fill0_.position=position20_.id left outer join ( select id, version, basis, symbol, fiat, 1 as clazz_ from currency ) asset21_ on position20_.asset=asset21_.id left outer join exchange exchange22_ on position20_.exchange=exchange22_.id left outer join market market23_ on position20_.market=market23_.id left outer join portfolio portfolio24_ on position20_.portfolio=portfolio24_.id where fill0_.id=unhex('05c5648c00444f5a9d3b1ee7d54325aa')

**Comment by douggie** [comment]
Think it might require to locking type to be pessimistic.

**Comment by douggie** [comment]
think i figured it out.

**Comment by timolson** [comment]
Did you use pessimistic locking or…?

**Comment by douggie** [comment]
nope, it was just that entities where cascading a merge before they were
originally persisted, in addition the ID was not get set on positions as
they were created, but getting persisted on a cascade merge with a new id.
still testing.

basically I was persisting children before parents.
