### ISSUE TITLE
buy antlr command error parsing

### ISSUE THREAD

**Issue by abraxas1984** [timolson/cointrader#138]
Hi there, this is a really interesting project, but I can't get the buy/sell commands to work. I'm trying to stick to this syntac:
buy/sell {volume} {market} [limit {limitPrice}] [stop {stopPrice}]

ct> buy 10.0 bitstamp:btc.usd

But get a token recognition error. How can I get around this?? Thanks

1) null returned by binding at org.cryptocoinpartners.schema.GeneralOrderFactory.create()
 but parameter 2 of org.cryptocoinpartners.schema.GeneralOrder.<init>() is not @Nullable
  while locating org.cryptocoinpartners.schema.Listing annotated with @com.google.inject.assistedinject.Assisted(value=)
    for parameter 2 at org.cryptocoinpartners.schema.GeneralOrder.<init>(GeneralOrder.java:85)
  while locating org.cryptocoinpartners.schema.GeneralOrder annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1)

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
    at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:770) ~[guice-assistedinject-4.0.jar:na]
    at com.sun.proxy.$Proxy40.create(Unknown Source) ~[na:na]
    at org.cryptocoinpartners.command.OrderCommand.run(OrderCommand.java:54) ~[classes/:na]
    at org.cryptocoinpartners.bin.ConsoleRunMode.run(ConsoleRunMode.java:94) ~[classes/:na]
    at org.cryptocoinpartners.bin.Main.main(Main.java:141) [classes/:na]
Internal error: see cointrader.log

**ct> line 1:13 token recognition error at: ':'
line 1:17 token recognition error at: '.u'**

**Comment by douggie** [comment]
let me check in a fix,

**Comment by timolson** [comment]
​Not sure if Douggie will chime in here or not but…
CoinTrader is really meant to be a programming framework for writing
automated trading bots in Java.  We haven't really maintained the console,
which is really just a demo.​

**Comment by abraxas1984** [comment]
I want to integrate this with other frameworks... I think the console would be great as a test tool to check the functionality.at the moment a lot of tables in db are empty and wanted to see how transactions are stored.
don't worry too much about it unless is an easy fix. I don't know much about antlr parser unfortunately
