### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by teklaon** [timolson/cointrader#139]
I would like to know if it is possible to trade between the markets on xchange? Example I buy a btc on btc-e at 700 usd and I resell it to 710 usd on poloniex directly from xchange. thank you for your reply

**Comment by douggie** [comment]
Yes, perfectly posssible. Cointrader will maintain positions on a per
exchange badis for you.

**Comment by teklaon** [comment]
Thank you very much for your repliy.

Excuse me for asking another question but I did not understand. As I search everywhere and especially on bitcointalk and I am told that it is not possible to do this

  From cointrader is it possible to buy bitcoin from btc-e.com and sell this bitcoin from btc-e.com to poloniex?

If possible I could have a tutorial to do it

Thank you

**Comment by teklaon** [comment]
exemple here

https://bitcointalk.org/index.php?topic=215881.0

http://bitcoin.stackexchange.com/questions/12670/why-dont-people-buy-at-one-exchange-and-sell-at-another

**Comment by douggie** [comment]
Hi,

you would do something like this

1) set up account btc-e and poloniex. Deposit fiat into BTC-e i.e USD, then
use that to buy BTC, then transfer BTC to poloniex BTC wallet and sell the
BTC to USD their. You would then need to transfer the USD back to BTC-E
bank account (which can take days) then repeat, of if you have a large
balance on both you can manage to write an algo to take advantage of prices
on both markets and move BTC back and forth to avoid delays.
2) build a strategy in cointrader that will take prices in from btc-e
and poloniex
and will determine when to buy and sell for you. All the order placement
API's are in place and built. We have not built any API's to transfer funds
between exchanges, but this is pretty trivial and could be something you
might like to contribute. Essentially can you can use cointrader to fully
automate what you would do manually so it can run 24x7 without any human
intervention, the key is you need to have a defined set of profitable
trading rules that you can automate using cointrader's complex event
processing engine, esper (
http://www.espertech.com/esper/solution_patterns.php).

Good luck

Regards

Douggie
