### ISSUE TITLE
Running BookTest in Eclipse failed due to failed db initialization

### ISSUE THREAD

**Issue by AmarRSingh** [timolson/cointrader#140]
I'm not sure what I'm doing wrong or if I'm supposed to be doing something different but when I ran BookTest in the Eclipse Java IDE, I received the following from the output (which has an error--scroll down to the very bottom):

2017-05-27 17:43:30 [main] WARN  o.cryptocoinpartners.util.ConfigUtil - Could not find configuration file "cointrader.properties"
2017-05-27 17:43:31 [main] DEBUG o.cryptocoinpartners.util.ConfigUtil - Combined Configuration:
awt.toolkit=sun.lwawt.macosx.LWCToolkit
base.symbol=USD
command.path=
console.cursor=ct>
console.hisory.size=100
db.bar.writer.threads=5
db.book.writer.threads=10
db.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
db.driver=com.mysql.jdbc.Driver
db.idle.test.period=3000
db.marketdata.writer.threads=5
db.max.connection.age=3600
db.persist.retry=4
db.pool.growth=35
db.pool.size=20
db.replay.reader.threads=5
db.test.connection=false
db.trade.writer.threads=5
db.url=jdbc:mysql://localhost:3306/cointrader
db.username=root
db.writer.delay=1000
faketicker.exchange=BITSTAMP
file.encoding.pkg=sun.io
file.encoding=UTF-8
file.separator=/
fill.processing.threads=2
gopherProxySet=false
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
java.class.path=/Users/amars_000/adr/cointrader/target/test-classes:/Users/amars_000/adr/cointrader/target/classes:/Users/amars_000/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/amars_000/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/amars_000/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/Users/amars_000/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.5/log4j-over-slf4j-1.7.5.jar:/Users/amars_000/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar:/Users/amars_000/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar:/Users/amars_000/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar:/Users/amars_000/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/amars_000/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/amars_000/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar:/Users/amars_000/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar:/Users/amars_000/.m2/repository/net/sourceforge/collections/collections-generic/4.01/collections-generic-4.01.jar:/Users/amars_000/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/amars_000/.m2/repository/com/tictactec/ta-lib/0.4.0/ta-lib-0.4.0.jar:/Users/amars_000/.m2/repository/com/espertech/esper/4.9.0/esper-4.9.0.jar:/Users/amars_000/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar:/Users/amars_000/.m2/repository/org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar:/Users/amars_000/.m2/repository/org/antlr/stringtemplate/3.2/stringtemplate-3.2.jar:/Users/amars_000/.m2/repository/cglib/cglib-nodep/2.2/cglib-nodep-2.2.jar:/Users/amars_000/.m2/repository/com/beust/jcommander/1.30/jcommander-1.30.jar:/Users/amars_000/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar:/Users/amars_000/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/amars_000/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/amars_000/.m2/repository/com/google/inject/extensions/guice-persist/4.0/guice-persist-4.0.jar:/Users/amars_000/.m2/repository/com/google/inject/extensions/guice-assistedinject/4.0/guice-assistedinject-4.0.jar:/Users/amars_000/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-core/4.0.0-SNAPSHOT/xchange-core-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/org/java-websocket/Java-WebSocket/1.3.0/Java-WebSocket-1.3.0.jar:/Users/amars_000/.m2/repository/com/github/mmazi/rescu/1.8.1/rescu-1.8.1.jar:/Users/amars_000/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.0/jackson-databind-2.5.0.jar:/Users/amars_000/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.0/jackson-annotations-2.5.0.jar:/Users/amars_000/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.0/jackson-core-2.5.0.jar:/Users/amars_000/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar:/Users/amars_000/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar:/Users/amars_000/.m2/repository/net/iharder/base64/2.3.8/base64-2.3.8.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-bitfinex/4.0.0-SNAPSHOT/xchange-bitfinex-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-bitstamp/4.0.0-SNAPSHOT/xchange-bitstamp-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/pusher/pusher-java-client/0.3.1/pusher-java-client-0.3.1.jar:/Users/amars_000/.m2/repository/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-btcchina/4.0.0-SNAPSHOT/xchange-btcchina-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/quickfixj/quickfixj-core/1.5.3-bd/quickfixj-core-1.5.3-bd.jar:/Users/amars_000/.m2/repository/quickfixj/quickfixj-msg-fix44/1.5.3-bd/quickfixj-msg-fix44-1.5.3-bd.jar:/Users/amars_000/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/amars_000/.m2/repository/com/github/nkzawa/socket.io-client/0.2.0/socket.io-client-0.2.0.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-btce/4.0.0-SNAPSHOT/xchange-btce-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-cryptsy/4.0.0-SNAPSHOT/xchange-cryptsy-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-coinbase/4.0.0-SNAPSHOT/xchange-coinbase-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-bter/4.0.0-SNAPSHOT/xchange-bter-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-campbx/4.0.0-SNAPSHOT/xchange-campbx-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar:/Users/amars_000/.m2/repository/org/jadira/usertype/usertype.core/3.1.0.CR6/usertype.core-3.1.0.CR6.jar:/Users/amars_000/.m2/repository/org/jadira/usertype/usertype.spi/3.1.0.CR6/usertype.spi-3.1.0.CR6.jar:/Users/amars_000/.m2/repository/org/hibernate/hibernate-core/4.3.11.Final/hibernate-core-4.3.11.Final.jar:/Users/amars_000/.m2/repository/org/jboss/logging/jboss-logging/3.1.3.GA/jboss-logging-3.1.3.GA.jar:/Users/amars_000/.m2/repository/org/jboss/logging/jboss-logging-annotations/1.2.0.Beta1/jboss-logging-annotations-1.2.0.Beta1.jar:/Users/amars_000/.m2/repository/org/jboss/spec/javax/transaction/jboss-transaction-api_1.2_spec/1.0.0.Final/jboss-transaction-api_1.2_spec-1.0.0.Final.jar:/Users/amars_000/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/Users/amars_000/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar:/Users/amars_000/.m2/repository/org/hibernate/common/hibernate-commons-annotations/4.0.5.Final/hibernate-commons-annotations-4.0.5.Final.jar:/Users/amars_000/.m2/repository/org/hibernate/javax/persistence/hibernate-jpa-2.1-api/1.0.0.Final/hibernate-jpa-2.1-api-1.0.0.Final.jar:/Users/amars_000/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar:/Users/amars_000/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/amars_000/.m2/repository/org/jboss/jandex/1.1.0.Final/jandex-1.1.0.Final.jar:/Users/amars_000/.m2/repository/org/hibernate/hibernate-entitymanager/4.3.11.Final/hibernate-entitymanager-4.3.11.Final.jar:/Users/amars_000/.m2/repository/org/hibernate/hibernate-c3p0/4.3.11.Final/hibernate-c3p0-4.3.11.Final.jar:/Users/amars_000/.m2/repository/org/hibernate/hibernate-ehcache/4.3.11.Final/hibernate-ehcache-4.3.11.Final.jar:/Users/amars_000/.m2/repository/net/sf/ehcache/ehcache-core/2.4.3/ehcache-core-2.4.3.jar:/Users/amars_000/.m2/repository/mysql/mysql-connector-java/5.1.29/mysql-connector-java-5.1.29.jar:/Users/amars_000/.m2/repository/org/reflections/reflections/0.9.9-RC1/reflections-0.9.9-RC1.jar:/Users/amars_000/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/amars_000/.m2/repository/com/bethecoder/ascii-table/1.0/ascii-table-1.0.jar:/Users/amars_000/.m2/repository/net/sf/opencsv/opencsv/2.0/opencsv-2.0.jar:/Users/amars_000/.m2/repository/com/clutch/dates/stringtotime/1.0.6/stringtotime-1.0.6.jar:/Users/amars_000/.m2/repository/org/springframework/spring-beans/2.5.5/spring-beans-2.5.5.jar:/Users/amars_000/.m2/repository/org/springframework/spring-core/2.5.5/spring-core-2.5.5.jar:/Users/amars_000/.m2/repository/org/antlr/antlr4-runtime/4.2.2/antlr4-runtime-4.2.2.jar:/Users/amars_000/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.jar:/Users/amars_000/.m2/repository/org/antlr/antlr4-annotations/4.2.2/antlr4-annotations-4.2.2.jar:/Users/amars_000/.m2/repository/com/github/nkzawa/engine.io-client/0.3.0/engine.io-client-0.3.0.jar:/Users/amars_000/.m2/repository/org/json/json/20090211/json-20090211.jar:/Users/amars_000/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar:/Users/amars_000/.m2/repository/jline/jline/2.12/jline-2.12.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-bittrex/4.0.0-SNAPSHOT/xchange-bittrex-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/com/xeiam/xchange/xchange-okcoin/4.0.0-SNAPSHOT/xchange-okcoin-4.0.0-SNAPSHOT.jar:/Users/amars_000/.m2/repository/io/netty/netty-all/4.1.0.Beta3/netty-all-4.1.0.Beta3.jar:/Users/amars_000/.m2/repository/com/mchange/c3p0/0.9.5/c3p0-0.9.5.jar:/Users/amars_000/.m2/repository/com/mchange/mchange-commons-java/0.2.9/mchange-commons-java-0.2.9.jar:/Users/amars_000/.m2/repository/nz/ac/waikato/cms/weka/weka-dev/3.7.11/weka-dev-3.7.11.jar:/Users/amars_000/.m2/repository/net/sf/squirrel-sql/thirdparty-non-maven/java-cup/0.11a/java-cup-0.11a.jar:/Users/amars_000/.m2/repository/org/pentaho/pentaho-commons/pentaho-package-manager/1.0.8/pentaho-package-manager-1.0.8.jar:/Users/amars_000/.m2/repository/pentaho/weka/pdm-timeseriesforecasting-ce/1.0/pdm-timeseriesforecasting-ce-1.0.jar:/Users/amars_000/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
java.class.version=52.0
java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/endorsed
java.ext.dirs=/Users/amars_000/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre
java.io.tmpdir=/var/folders/vr/v6ty6h051xb2s1s_rg7j7qzh0000gn/T/
java.library.path=/Users/amars_000/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_101-b13
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.vendor.url=http://java.oracle.com/
java.vendor=Oracle Corporation
java.version=1.8.0_101
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.101-b13
jline.WindowsTerminal.directConsole=false
line.separator=
module.path=
os.arch=x86_64
os.name=Mac OS X
os.version=10.10.5
path.separator=:
project.artifactId=cointrader
project.groupId=org.cryptocoinpartners
project.version=0.3.0-SNAPSHOT
sun.arch.data.model=64
sun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/classes
sun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib
sun.cpu.endian=little
sun.cpu.isalist=
sun.io.unicode.encoding=UnicodeBig
sun.java.command=org.cryptocoinpartners.schema.BookTest
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=UTF-8
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=unknown
user.country=US
user.dir=/Users/amars_000/adr/cointrader
user.home=/Users/amars_000
user.language=en
user.name=amars_000
user.timezone=America/New_York
xchange.bitfinex.class=com.xeiam.xchange.bitfinex.v1.BitfinexExchange
xchange.bitfinex.helper.class=BitfinexHelper
xchange.bitfinex.rate.period=5
xchange.bitfinex.rate.queries=3
xchange.bitstamp.class=com.xeiam.xchange.bitstamp.BitstampExchange
xchange.bitstamp.rate.period=5
xchange.bitstamp.rate.queries=1
xchange.btcchina.class=com.xeiam.xchange.btcchina.BTCChinaExchange
xchange.btcchina.rate.period=2
xchange.btcchina.rate.queries=1
xchange.btce.class=com.xeiam.xchange.btce.v3.BTCEExchange
xchange.btce.rate.period=5
xchange.btce.rate.queries=3
xchange.bter.class=com.xeiam.xchange.bter.BTERExchange
xchange.bter.rate.period=5
xchange.bter.rate.queries=3
xchange.campbx.class=com.xeiam.xchange.campbx.CampBXExchange
xchange.campbx.rate.period=1
xchange.campbx.rate.queries=1
xchange.coinbase.class=com.xeiam.xchange.coinbase.CoinbaseExchange
xchange.coinbase.rate.period=5
xchange.coinbase.rate.queries=1
xchange.cryptsy.class=com.xeiam.xchange.cryptsy.CryptsyExchange
xchange.cryptsy.rate.period=2
xchange.cryptsy.rate.queries=1
xchange.okcoin.class=com.xeiam.xchange.okcoin.OkCoinExchange
xchange.okcoin.exchangeSpecificParameters.futures=false
xchange.okcoin.exchangeSpecificParameters.intl=true
xchange.okcoin.rate.period=5
xchange.okcoin.rate.queries=3
xchange.okcoin_month.class=com.xeiam.xchange.okcoin.OkCoinExchange
xchange.okcoin_month.exchangeSpecificParameters.futures=true
xchange.okcoin_month.exchangeSpecificParameters.intl=true
xchange.okcoin_month.rate.period=5
xchange.okcoin_month.rate.queries=3
xchange.okcoin_nextweek.class=com.xeiam.xchange.okcoin.OkCoinExchange
xchange.okcoin_nextweek.exchangeSpecificParameters.futures=true
xchange.okcoin_nextweek.exchangeSpecificParameters.intl=true
xchange.okcoin_nextweek.rate.period=5
xchange.okcoin_nextweek.rate.queries=3
xchange.okcoin_quarter.class=com.xeiam.xchange.okcoin.OkCoinExchange
xchange.okcoin_quarter.exchangeSpecificParameters.futures=true
xchange.okcoin_quarter.exchangeSpecificParameters.intl=true
xchange.okcoin_quarter.rate.period=5
xchange.okcoin_quarter.rate.queries=3
xchange.okcoin_thisweek.class=com.xeiam.xchange.okcoin.OkCoinExchange
xchange.okcoin_thisweek.exchangeSpecificParameters.futures=true
xchange.okcoin_thisweek.exchangeSpecificParameters.intl=true
xchange.okcoin_thisweek.rate.period=5
xchange.okcoin_thisweek.rate.queries=3
2017-05-27 17:43:31 [main] INFO  org.cryptocoinpartners.persist - initializing persistence
**Exception in thread "main" java.lang.Error: Could not initialize db
	at org.cryptocoinpartners.util.PersistUtil.init(PersistUtil.java:808)
	at org.cryptocoinpartners.util.PersistUtil.init(PersistUtil.java:707)
	at org.cryptocoinpartners.schema.BookTest.init(BookTest.java:88)
	at org.cryptocoinpartners.schema.BookTest.main(BookTest.java:24)
Caused by: java.lang.ExceptionInInitializerError
	at org.cryptocoinpartners.util.PersistUtil.ensureSingletonsExist(PersistUtil.java:821)
	at org.cryptocoinpartners.util.PersistUtil.init(PersistUtil.java:801)
	... 3 more
Caused by: java.lang.NullPointerException
	at org.cryptocoinpartners.util.EM.sqlQueryOne(EM.java:343)
	at org.cryptocoinpartners.util.EM.queryOne(EM.java:314)
	at org.cryptocoinpartners.schema.Currency.forSymbol(Currency.java:43)
	at org.cryptocoinpartners.schema.Currency.forSymbolOrCreate(Currency.java:61)
	at org.cryptocoinpartners.schema.Currencies.fiat(Currencies.java:200)
	at org.cryptocoinpartners.schema.Currencies.<clinit>(Currencies.java:9)
	... 5 more**

**Comment by douggie** [comment]
Most likley the database rest command has not been run. Think this is on
the readme. It will create all the table and populate statics for you.

**Comment by timolson** [comment]
Database "reset" command that is. See Readme
