### ISSUE TITLE
QUESTION: Recovery from outages

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#144]
Hi Tim --

Interesting project.  I've been unable to work out if it recovers fully from a loss of connection though.

For example if it places a buy order which, during an outage, fills, and I would like that fill to trigger the placement of specific sell orders, will all that happen automatically on a restart or reconnection, or is manual intervention required?

(NB Can't see how to TAG this question, sorry)

**Comment by douggie** [comment]
the xchange project is stateless polling api. depending on when the
disconnect happend you would need to handle the exception generated by
xchange accordingly and main the order state within your application.

here is an example of a class that keeps track of orders and uses the
xchange libs to update the state.

https://github.com/timolson/cointrader/blob/master/src/main/java/org/cryptocoinpartners/module/xchange/XchangeOrderService.java

**Comment by IanWorthington** [comment]
Thanks Douggie --

Not quite sure what you mean by: 

> main the order state within your application.

**Comment by douggie** [comment]
sorry i mean maintain not main!

**Comment by IanWorthington** [comment]
Hi Douggie --

So, if I understand you correctly after a disconnect I simply need code to pull down the new order status?

**Comment by douggie** [comment]
correct, if you disconnect, reconnect and request using the exchange
provided order id to get the latest state.

**Comment by douggie** [comment]
Hi Ian,

Sorry this got mixed up an exchange thread.

Cointrader maintains all the order state for you and reconnects and determines the latest state. If cointrader fails, it recovers the state from the DB then connects to each exchange and reconciles the latest order state for you at start up.
There are also some JMX commands that allow you to create manual fill and order operations at runtime in the event something goes seriously wrong.

For performance the DB is persisted as a lazy write via a blocking queue, this queue is not durable so if you had a tonne of messages and a slow DB, this queue would back up, if you then restarted coin trader the state of stuff that was in the queue would be lost, in reality I have not see this happen.

**Comment by IanWorthington** [comment]
Thanks Douggie.
