### ISSUE TITLE
Is master a working version?

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#145]
Hi @douggie 

Looking at trying to build this, but right off the bat Eclipse is flagging code errors:

http://i67.tinypic.com/2j3gzeo.jpg

(there's a few more that don't fit on the screen)

Is this expected?

**Comment by douggie** [comment]
Hi,

It builds ok, these look like issues related to JPA/Hibernate, could it be a particular eclipse plug in causing these.

Can you build from the command line via `mvn install` ?

**Comment by IanWorthington** [comment]
@douggie It was the Eclipse JPA validator.  Turned it off. Maven compiles it just fine.
