### ISSUE TITLE
Problem with connecting to Mysql database

### ISSUE THREAD

**Issue by anhtuantt** [timolson/cointrader#147]
Hello,
I want to research cointrader project and  implement my own ideas. When I run the Main class (from the latest source code of github), I got the problem "Unable to resolve name [org.cryptocoinpartners.util.PhysicalNamingStrategyImpl]", look like this class is not found. Please advice.

More detail stack trace:
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.cryptocoinpartners.util.PhysicalNamingStrategyImpl] as strategy [org.hibernate.boot.model.naming.PhysicalNamingStrategy]
  at org.cryptocoinpartners.module.ApplicationInitializer.<init>(ApplicationInitializer.java:68)
  at org.cryptocoinpartners.module.ApplicationInitializer.class(ApplicationInitializer.java:33)
  while locating org.cryptocoinpartners.module.ApplicationInitializer

Regards,
Tuan Nguyen.

**Comment by douggie** [comment]
Updated and pushed.

**Comment by anhtuantt** [comment]
It works! Thank you very much.
