### ISSUE TITLE
Location of cointrader.properties

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#148]
@douggie --

Where does cointrader search for cointrader.properties?  Having it in the target folder works but it gets blown away on every mvn clean.  What's a better location?

**Comment by douggie** [comment]
it uses current class path so just in your src folder should be good.

**Comment by IanWorthington** [comment]
Maybe not the best idea if it contains the secret api keys as there's a danger of it being pushed up.  Sounds as though launching from a directory outside of the development tree is the way to do.

**Comment by douggie** [comment]
Definitely better ways to do this, there has been an open issues for a while (https://github.com/timolson/cointrader/issues/29) just have not get round to it, happy for a PR though!
