### ISSUE TITLE
How to Add an XChange

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#152]
I'm looking at adding support for cryptopia.

On Tim's page "How to Add an XChange", item no 2 is:

o add a singleton entry to Markets

Is this page maybe out of date?  I can't find a Markets, nor a list of singletons that represent markets.  Does he maybe mean Exchanges.java, which does seem to contain a list of some but not all exchanges (gdax for instance isn't there but does appear to work)?

**Comment by douggie** [comment]
1) add to pom.xml
```                              <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-[exchange]</artifactId>
            <version>${xchange.version}</version>
        </dependency>```
2) add static to Exchanges.java i.e.
`	public static final Exchange  = Exchange.forSymbolOrCreate("BITMEX", 1, 0.002, 0.002, 0, 0, FeeMethod.PercentagePerUnit, 0.25, 0,
			FeeMethod.PercentagePerUnit, false);
}`
3) create helper class to handel any exchange specific logic (there is always some especially on the order side of things!)
3) add to cointrader.properties
```xchange.bittrex.class=org.knowm.xchange.bittrex.BittrexExchange
xchange.kraken.helper.class=
#fires queries every 30 seconds 20 at a time
xchange.bittrex.rate.queries=2
xchange.bittrex.rate.period=8
xchange.bittrex.listings=XRP.BTC,ETH.BTC,LTC.BTC,NXT.BTC,DCR.BTC,XLM.BTC,QTUM.BTC,WAVES.BTC,MAID.BTC,SALT.BTC,PAY.BTC,XZC.BTC,PIVX.BTC,DCR.BTC,STEEM.BTC,ADA.BTC,REP.BTC,CVC.BTC,BAT.BTC,GNO.BTC
```

**Comment by IanWorthington** [comment]
What does that static in Exchanges actually do?  The (admittedly limited, certainly no orders) testing I've done to date doesn't seem to object to it missing.

**Comment by douggie** [comment]
allows you to define exchange specific parameters such as fees, margin
rates, fee methods, margin methods, miniumum order sizes etc.

**Comment by douggie** [comment]
or you can just add/updaye such params to the exchange, market or prompt
tables at a later date.
