### ISSUE TITLE
Trigger on order fill?

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#154]
@douggie --

What's the best way of triggering an action when one of my outstanding orders fills?

**Comment by douggie** [comment]
cointrader will calculate a fill for you, as the exchanges don't provide
fills via the API, instead you get an order update between pollings of a
working amount and an average price, cointrader will create a fill for that
amount and price it it changes between two polling intervals, it will then
update the positions closing out on a fifo basis as well as manage the
order state.

You can either subscribe to the fill when it is published by the order
service

@When("@Priority(9) select * from Fill")

public void handleFill(Fill fill) {

}


or when the order changes to a filled or part-filled state

@When("@Priority(7) select * from OrderUpdate where OrderUpdate.state =
OrderState.FILLED or  OrderUpdate.state = OrderState.PARTFILLLED")

public void handleOrderUpdate(OrderUpdate orderUpdate) {

}


or when the position is updated

@When("@Priority(9) @Audit select * from PositionUpdate")

void handlePositionUpdate(PositionUpdate positionUpdate) {

}
