### ISSUE TITLE
unable to run multiple inbound threads

### ISSUE THREAD

**Issue by douggie** [timolson/cointrader#77]
When updating the esper configuration to have one or more threads to handle 
 all Subscriber / Listener Tasks, the Portfolio fields are not available in the inbound threads.

Probably just need to declare them as static so there is one per class, other ideas welcomed.

Example config (cointrader-esper.cfg)
<threading>
			      <threadpool-outbound enabled="true" num-threads="1"/>
     				<internal-timer enabled="false" msec-resolution="200"/>
				 <listener-dispatch preserve-order="true" timeout-msec="100000" locking="spin"/>
</threading> 

Example Field
	private ConcurrentHashMap<Asset, ConcurrentHashMap<Exchange, ConcurrentHashMap<Listing, ArrayList<Position>>>> positions;

Example Code
Collection<Position> getPositions(Asset asset, Exchange exchange) {
		ArrayList<Position> allPositions = new ArrayList<Position>();
		if (positions.get(asset) != null && positions.get(asset).get(exchange) != null) {
			Iterator<Listing> itl = positions.get(asset).get(exchange).keySet().iterator();
			while (itl.hasNext()) {
				Listing listing = itl.next();

				Iterator<Position> itp = positions.get(asset).get(exchange).get(listing).iterator();
				while (itp.hasNext()) {
					Position pos = itp.next();
					allPositions.add(pos);
				}

			}
		}

		return allPositions;

	}

**Comment by timolson** [comment]
​Instead of static fields, it's probably better to use a singleton pattern.​

**Comment by douggie** [comment]
Yeah, few other issues when you spin it up with multiple threads. For some
reason the book data is processed again. Post persit so the clear blobs has
been completed. No idea why as yet. Few other little issues with concurrent
access to objects fixed up.

Hope you had a good new year!!!!
