### ISSUE TITLE
Managing code quality with SonarQube

### ISSUE THREAD

**Issue by jule64** [timolson/cointrader#79]
Hi Tim and Douggie

Is this something you are using or would be interested to use for Cointrader?

Thanks

Julien

**Comment by timolson** [comment]
I'm not opposed, but we are not a huge project and I do find many software metrics to be of dubious value.  Is there something particular about SonarQube you'd like to highlight?  Or are you just looking for some general code analysis?

By the way, I added Coin Trader to OpenHub a while back:
https://www.openhub.net/p/cointrader

**Comment by jule64** [comment]
I have used it on a couple of projects and found it helped, although you are right it's less useful on smaller projects.  Nevertheless I thought I could run a quick analysis and see what comes up.  I doubt it will be anything but some minor stuff but I could then potentially work on those and commit?  It also has indicators like technical debt, dependency analysis etc. although I have not used those much.

**Comment by jule64** [comment]
Nice link by the way!

**Comment by timolson** [comment]
I didn't mean to sound bitchy.  Totally happy to have you incorporate SonarQube and do some cleanup.

**Comment by jule64** [comment]
Awesome, thanks!

**Comment by douggie** [comment]
Hi,

Im sure my code could do with some clean up. 5 to 10 mins here and there
leads to pretty inconsitent code. Although we now have :

• Backtesting
• Real time balances balances on fifo closeouts
• conversion of balances  to base currency
• best bid/best offer implied prices
•  talib indicators
• ohlc bars supporr
• persitance of all orders,fills and transactions
• bitcoin derivatives and underlying support
• additional exchanges such cryptsy, okcoin etc

**Comment by jule64** [comment]
That's some pretty nice features there!  I'll try to do a run this weekend and let you know if it returns anything useful.  Thanks again guys

**Comment by jule64** [comment]
Hi guys,

I ran an analysis yesterday and as expected only minor stuff came up. In fact the project has a technical debt ratio of just 5% and a SQALE rating "A" which means top grade! :)

So as discussed I have started to do some clean up and started committing my changes (I will do that by issue type as much as possible).  I am appending the word "cleanup" to my commit messages to signal it's part of the same exercise.

If you are happy with that I can start sending pull requests!

Thanks

**Comment by timolson** [comment]
In that case I LOVE metrics  :D

**Comment by jule64** [comment]
I added the sonar plugin info to the pom (just three lines) is it ok for me to commit that?

**Comment by timolson** [comment]
Sure!

**Comment by douggie** [comment]
Hi julian,

Great news!!!

I was a bit naughty and commented out blocks, feel free to remove all the
commented code blocks.

There is a little inconsistent naming of some objects so a quick refactor
their.

I suspect it is some of the exception handeling that code be a bit better.
I spent quite a bit of time tidying up data structures to avoid concurrency
issues.

Thanks once again.

**Comment by jule64** [comment]
No probs will look at that, I might need some guidance with what to do with the exception handling and renaming when I come to that

Cheers

**Comment by jule64** [comment]
Hi guys, in case I'm in doubt about some of the fixes/cleanups I work on what's the best way to check with you first?  Should I open a new thread and ask my questions there or just carry on on this one?

**Comment by timolson** [comment]
This thread is fine I think

**Comment by jule64** [comment]
Are you happy for the "e.printStackTrace()" to be logged instead?

**Comment by timolson** [comment]
Not so much, we should get that into slf4j.  I may have used console printout in a few isolated test cases

**Comment by jule64** [comment]
Tim and Douggie, there are a few floating points equality tests being flagged in the following classes: CompareUtils.java	10
   Market.java	3
   Listing.java	3
   DiscreteAmount.java 2
Are any of those worth fixing? (with something like Math.abs(a - b) < 1E-15)  ?

**Comment by jule64** [comment]
In PersistUtil, line 45,  if (persisted) {...} is always false due to line 43 (persisted = false;), happy to remove line 43?

**Comment by jule64** [comment]
or should it be "if (!persisted) {...}" instead?

**Comment by timolson** [comment]
I tried reviewing these float compares but the line numbers seem to be the class declarations, not the lines where the comparison is.  Can you specify the line numbers instead?

**Comment by timolson** [comment]
I cleaned up that code in PersistUtil with commit 47b1db67db998e090919ca46305010daadd49ded

**Comment by jule64** [comment]
Sure, I'll send more details when I get home this evenings. That makes me think would you be interested in taking a look at the dashboard i am using?

**Comment by jule64** [comment]
Thanks a lot

**Comment by timolson** [comment]
If you can't copy-paste line numbers, maybe a screenshot would do.

**Comment by jule64** [comment]
Hi Tim, I've pasted the details below:

 cointrader  src/main/java/org/cryptocoinpartners/schema/DiscreteAmount.java
L93    
L227    
 cointrader  src/main/java/org/cryptocoinpartners/schema/Listing.java
L135    
L162    
L182    
 cointrader  src/main/java/org/cryptocoinpartners/schema/Market.java
L81    
L94    
L121    
 cointrader  src/main/java/org/cryptocoinpartners/util/CompareUtils.java
L117    
L136    
L155    
L156    
L157    
L158    
L159    
L160    
L161    
L162

**Comment by timolson** [comment]
Sorry I haven't followed up with this yet.  I haven't forgotten and will hopefully get to it soon.

**Comment by jule64** [comment]
No problem Tim and thanks for the update.  I have not been doing much new cleanups lately but was planning to do a few this weekend and perhaps send you another PR after.
Julien
