### ISSUE TITLE
import exceptions

### ISSUE THREAD

**Issue by jule64** [timolson/cointrader#80]
Got import exceptions in XchangeData.java and XchangeOrderService.java after updating my copy today.  Problem lines are:
import com.xeiam.xchange.service.polling.PollingMarketDataService;
import com.xeiam.xchange.NotYetImplementedForExchangeException;
import com.xeiam.xchange.service.polling.PollingTradeService;

Correct imports are:
import com.xeiam.xchange.service.polling.marketdata.PollingMarketDataService;
import com.xeiam.xchange.exceptions.NotYetImplementedForExchangeException;
import com.xeiam.xchange.service.polling.trade.PollingTradeService;

**Comment by timolson** [comment]
We are building against a SNAPSHOT version of XChange: version 2.2.0-SNAPSHOT, which is still unreleased.  Looks like the XChange project has modified these package names.  I will check in a fix presently...

**Comment by douggie** [comment]
Sorry, my fault. It was a build i did for the xchange team to support ok
coin futures. It is now in their prod sbapshot.

If you don't get a chance i can update in a few hours!

**Comment by timolson** [comment]
Already done, easy

**Comment by douggie** [comment]
Thanks tim!

**Comment by jule64** [comment]
This has come back ..

**Comment by douggie** [comment]
Ill take a look in a bit

**Comment by douggie** [comment]
Fixed

**Comment by douggie** [comment]
Fixed.

Might need to do tge following

Update maven dependancies
Clean project
Run maven install

Regards
On 7 Feb 2015 21:06, douggie@melvilleclarke.com wrote:

Fixed
On 7 Feb 2015 17:27, "Douggie melville-clarke" <douggie@melvilleclarke.com>
wrote:

Ill take a look in a bit

**Comment by jule64** [comment]
Thanks Douggie

**Comment by timolson** [comment]
Did you bump the XChange dep to 3.0.0 for this?  See Issue #82 now
