### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by shakey-uk** [timolson/cointrader#82]
Looks like there's no 3.0.0 XChange snapshot under https://oss.sonatype.org/content/repositories/snapshots/

This works:
`<xchange.version>3.0.1-SNAPSHOT</xchange.version>`

**Comment by timolson** [comment]
Possibly broken by changes for Issue #80.

Douggie?

**Comment by douggie** [comment]
Was me who bumped, i still had dev repo. Fixed abd pushed
