### ISSUE TITLE
Tabs / Spaces Cleanup

### ISSUE THREAD

**Issue by timolson** [timolson/cointrader#83]
It seems like we have developed a formatting problem with tabs & spaces, so we should clean this up.

Does anyone want to voice a preference for tabs vs spaces?  I think I used spaces initially because I like to align wrap-around lines with elements directly above them, which doesn't always match a tabstop.  Open to comments, though.

**Comment by jule64** [comment]
I personally don't have any strong preferences towards one or the other but that being said tabs do show up as a "minor" issue in Sonar (those are the default rules though)

**Comment by douggie** [comment]
Hi,

May be we could inculde a standard formatter to ensure consistancy. I have
been using elcipse with a tab based formatter. So i am to blame! Not sure
if we can share format.xml's between eclipse and intelij. Happy to migrate
to intelij if needed.

**Comment by timolson** [comment]
Personally, I'm not a fascist about code style: curly braces and spaces and such.  It was just the tabs thing that stood out because nothing is aligned and it's really hard to read.  If we can just settle on no-tabs or whatever, it's enough for me.  Opinions?

**Comment by douggie** [comment]
No tabs! Done. Will update my formatter!
