### ISSUE TITLE
Exceptions at startup

### ISSUE THREAD

**Issue by kyr7** [timolson/cointrader#88]
Hello! I`m trying to experiment with Cointrader. Unfortunately I get these babies at startup ( https://gist.github.com/kyr7/5b2261741491726d5aed ) . What could it mean?

P.S. I cheated and used Java 8, but seen others do it, so thought probably it`s ok.

**Comment by douggie** [comment]
Hi kyr7,

Will take a look tonight. I doubt it us haca 8. Most likey due to the move
to new xchange api to support futures.

**Comment by douggie** [comment]
Should be fixed now. Let me know how you get on

**Comment by kyr7** [comment]
Allright, null pointers are gone, but still I have these  "Unable to obtain CGLib fast method"
c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DecimalAmount org.cryptocoinpartners.schema.GeneralOrder.getStopPrice()
hash=1556211970 size=0

And these missing epls : o.cryptocoinpartners.module.Context - no module file found for DataCommand.epl on classpath. Please ensure DataCommand.epl is in the resources directory.

**Comment by douggie** [comment]
Hi kyr7,

They are just info level logs, everything should still work.

**Comment by kyr7** [comment]
Well I was trying to complete console demo, but couldn`t.
ct> data summary
2015-03-17 14:48:27 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for DataCommand.epl on classpath. Please ensure DataCommand.epl is in the resources directory.
2015-03-17 14:48:27 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for ReportCommand.epl on classpath. Please ensure ReportCommand.epl is in the resources directory.
2015-03-17 14:48:27 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for CommandBase.epl on classpath. Please ensure CommandBase.epl is in the resources directory.
no results

**Comment by timolson** [comment]
Those are probably spurious "errors" in the debug log.  Not every module (loadable directory) has an EPL file of Esper statements, and that is ok.  My latest push should fix this message.

Now, you also don't have any data in the DB, which is a different issue.  The console demo does *not* save data to the database!  It only streams the events in-memory.  Try running `cointrader.sh save-data` as a separate process, then after a minute try the console's `data summary` command.

**Comment by kyr7** [comment]
Thank you for the hint. Could also put the saving data part into the console demo description, to make it easy to kickstart?
