### ISSUE TITLE
ct> buy 10.0 bitfinex:btc.usd throws NPE

### ISSUE THREAD

**Issue by kyr7** [timolson/cointrader#89]
SpecificOrder.toString() produces npe because Order.getFillType() is assumed to be not null.

**Comment by douggie** [comment]
Hi kyr7,

Indeed we need to work on error habdeling.

If you specfiy limit you should be ok. We only currently support limit,
stop loss, stop limit.

**Comment by kyr7** [comment]
Thank you, Douggie. Got that.
